# type_defines.py - from pu-007/oxa-server
from typing import Dict, Literal, Optional, Protocol, TypedDict, Awaitable, Callable


class CommandResult(TypedDict):
    stdout: str
    stderr: str
    exit_code: int


class SpeakerProtocol(Protocol):
    """SpeakerManager 的接口协议，定义了所有可用的方法和属性"""

    status: Literal["playing", "paused", "idle"]

    async def get_playing(self, sync: bool = False) -> Literal["playing", "paused", "idle"]: ...
    async def set_playing(self, playing: bool = True) -> bool: ...
    async def play(
        self,
        text: Optional[str] = None,
        url: Optional[str] = None,
        buffer: Optional[bytes] = None,
        blocking: bool = True,
        timeout: int = 10 * 60 * 1000,
    ) -> bool: ...
    async def wake_up(self, awake: bool = True, silent: bool = True) -> bool: ...
    async def ask_xiaoai(self, text: str, silent: bool = False) -> bool: ...
    async def abort_xiaoai(self) -> bool: ...
    async def get_boot(self) -> str: ...
    async def set_boot(self, boot_part: Literal["boot0", "boot1"]) -> bool: ...
    async def get_device(self) -> Dict[str, str]: ...
    async def get_mic(self) -> Literal["on", "off"]: ...
    async def set_mic(self, on: bool = True) -> bool: ...
    async def run_shell(self, script: str, timeout: int = 10000) -> CommandResult: ...


ActionFunction = Callable[[SpeakerProtocol], Awaitable[None]]
Actions = list[str | ActionFunction]
